#!/usr/bin/python3
def is_sqr(number):
    """check if a number is squared"""
    import math

    x = int(math.sqrt(number))
    if (x * x == number):
        return (True)
    return (False)

def is_rsa(n):
    """split the rsa of a number"""
    import math
    from prime import is_prime

    x = int(math.sqrt(n)) + 1
    while True:
        y = x ** 2 - n
        if is_sqr(y):
            z = math.sqrt(y)
            break
        x = x + 1
    #print(is_prime(x + z))
    #print(is_prime(x - z))
    print("{:d}={:d}*{:d}".format(int(n), int(x + z), int(x - z)))

def start():
    """where to run the file"""
    import sys

    lis = sys.argv
    if len(lis) < 2:
        print("Error!: <USAGE> -> ./rsa filename")
        exit(98)
    f_name = ''
    if len(lis) == 2:
        f_name = lis[1]
    if len(lis) == 3:
        f_name = lis[2]
    with open(f_name ) as file_in:
        lines = []
        for line in file_in:
            lines.append(line);
    if len(lines) == 0:
        print("The file is empty")
        exit(98)
    is_rsa(int(lines[0]))
start()

